version: '3'
volumes:
  data:
services:
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: wfapplication
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - data:/var/lib/mysql
    ports:
      - "3306:3306"